# Generated by Django 4.2.9 on 2024-04-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2005-07-16'),
            preserve_default=False,
        ),
    ]
